apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.vrtuoso.service: socket-server-service
  name: socket-server-service
  namespace: {{ .Values.namespace | default "vrtuoso" }}
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.vrtuoso.service: socket-server-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.vrtuoso.service: socket-server-service
    spec:
      imagePullSecrets:
        - name: quay-regcred
      containers:
      - env:
        - name: PORT
          value: "7000"
        - name: REDIS_URL
          value: {{- if eq .Values.redis.incluster true }} {{ printf "redis://v:%s@redis.%s.svc.cluster.local:6379" .Values.redis.env.REDIS_PASSWORD (.Values.namespace | default "vrtuoso") }}
          {{- else }} {{ .Values.socketserver.env.REDIS_URL }}
          {{- end }}
        image: quay.io/vrtuoso/socket-server:{{ .Values.socketserver.image.tag | default .Values.image.tag | default "latest" }}
        name: socket-server-service
        ports:
        - containerPort: 7000
        resources: {}
      restartPolicy: Always
status: {}
