apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.vrtuoso.service: studio-service
  name: studio-service
  namespace: {{ .Values.namespace | default "vrtuoso" }}
spec:
  replicas: {{ .Values.studio.replicaCount | default 1 }}
  strategy: {}
  selector:
    matchLabels:
      io.vrtuoso.service: studio-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.vrtuoso.service: studio-service
    spec:
      imagePullSecrets:
        - name: quay-regcred
      containers:
      - env:
        - name: API_URL
          value: http://api-service.{{ .Values.namespace | default "vrtuoso" }}.svc.cluster.local:8080
        - name: DB_HOST
          value: {{ .Values.mysql.host }}
        - name: DB_NAME
          value: {{ .Values.mysql.database }}
        - name: DB_PASSWORD
          value: {{ .Values.mysql.password }}
        - name: DB_PORT
          value: {{ .Values.mysql.port | quote }}
        - name: DB_SSL
          value: {{ .Values.mysql.ssl }}
        - name: DB_USERNAME
          value: {{ .Values.mysql.username }}
        - name: ENV
          value: production
        - name: FFMPEG_PATH
          value: ffmpeg
        - name: HOST_URL
          value: {{ .Values.shared.env.HOST_URL }}
        - name: FILE_HOST_URL
          value: {{ .Values.studio.env.FILE_HOST_URL | default "" | quote}}
        - name: JWT_SECRET_KEY
          value: {{ .Values.shared.env.JWT_SECRET_KEY }}
        - name: INSTANCE_MODE
          value: cloud
        image: quay.io/vrtuoso/studio:{{ .Values.studio.image.tag | default .Values.image.tag | default "latest" }}
        name: studio-service
        resources: {}
      restartPolicy: Always
status: {}
