apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.vrtuoso.service: portal-ui-service
  name: portal-ui-service
  namespace: {{ .Values.namespace | default "vrtuoso" }}
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  selector:
    io.vrtuoso.service: portal-ui-service
status:
  loadBalancer: {}
