apiVersion: v1
kind: Service
metadata:
  labels:
    io.vrtuoso.service: socket-server-service
  name: socket-server-service
  namespace: {{ .Values.namespace | default "vrtuoso" }}
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  selector:
    io.vrtuoso.service: socket-server-service
status:
  loadBalancer: {}
