apiVersion: v1
kind: Service
metadata:
  labels:
    io.vrtuoso.service: studio-service
  name: studio-service
  namespace: {{ .Values.namespace | default "vrtuoso" }}
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    io.vrtuoso.service: studio-service
status:
  loadBalancer: {}
