apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb
  namespace: {{ .Values.namespace | default "vrtuoso" }}
  annotations:
    {{- if eq .Values.ingress.provider "rancher-v1" }}
    io.rancher.scheduler.global: "true"
    {{- end }}
    {{- if eq .Values.ingress.nginx true }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 99999m
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/send-timeout: "3600"
    nginx.ingress.kubernetes.io/read-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: socket-server-service
    nginx.org/websocket-services: socket-server-service
    {{- end }}
    {{- if ne .Values.tls.enabled true }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if eq .Values.tls.enabled true }}
  tls:
  - secretName: {{ .Values.tls.secretName | default "vrtuoso.io" }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /studio
        backend:
          serviceName: studio-service
          servicePort: 80
      - path: /v1/
        backend:
          serviceName: api-service
          servicePort: 8080
      - path: /socket.io
        backend:
          serviceName: socket-server-service
          servicePort: 7000
      - path: /
        backend:
          serviceName: portal-ui-service
          servicePort: 5002