apiVersion: v1
kind: Secret
metadata:
  name: quay-regcred
  namespace: {{ .Values.namespace | default "vrtuoso" }}
data:
  .dockerconfigjson: {{ .Values.registry.dockerConfigJson }}
type: kubernetes.io/dockerconfigjson