{{- if eq .Values.tls.enabled true }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tls.secretCrt }}
  tls.key: {{ .Values.tls.secretKey }}
kind: Secret
metadata:
  name: {{ .Values.tls.secretName | default "vrtuoso.io" }}
  namespace: {{ .Values.namespace | default "vrtuoso" }}
type: kubernetes.io/tls 
---
{{- end }}