namespace: vrtuoso
image:
  tag: release-v1
tls: 
  enabled: false
  secretName: ''
  secretCrt: ''
  secretKey: ''
ingress:
  provider: rancher-v1|digitalocean|gke|eks
shared:
  env:
    HOST_URL: https://portal.vrtuoso.io
    JWT_SECRET_KEY: secret
api:
  replicaCount: 1
  image: {}
  env:
    S3_ACCESS_KEY_ID: s3accesskeyid
    S3_SECRET_ACCESS_KEY: s3secret
    S3_BUCKET: s3bucket
    S3_ENDPOINT: https://s3.us-east-1.amazonaws.com
    S3_REGION: us-east-1
    SMTP_HOST: smtp.mailgun.org
    SMTP_PASSWORD: smtppass
    SMTP_PORT: 587
    SMTP_USERNAME: postmaster@mg.vrtuoso.io
portalui:
  replicaCount: 1
  image: {}
socketserver:
  replicaCount: 1
  image: {}
  env:
    REDIS_URL: redis://v:pass@redishost:6379 
studio:
  replicaCount: 1
  image: {}
registry:
  dockerConfigJson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJkbkowZFc5emJ5dGtaWEJzYjNrNk1qTkdPVXhGVVRVelVsbFlSVFJXV2xWRVRsSlRURFpZUXpWQk9FWldRVnBOVlRkRE4wa3dNMEU1VUU5UlF6
mysql:
  host: mysqlhost
  username: vrtuoso
  password: vrtuoso
  database: vrtuoso
  port: 3306
  ssl: disable
redis:
  image: {}
  incluster: false
  env:
    REDIS_PASSWORD: vrtuoso
