{{- if eq .Values.ingress.installNginxIngress true }}
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
{{- if eq .Values.ingress.provider "digitalocean-socket" }}
    service.beta.kubernetes.io/do-loadbalancer-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "b729fad9-d6b2-4ed5-8d4c-3eb13a4aaf65"
{{- end }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
{{- if eq .Values.ingress.provider "digitalocean-socket" }}
      targetPort: 80
{{- else }}
      targetPort: http
{{- end }}
    - name: https
      port: 443
{{- if eq .Values.ingress.provider "digitalocean-socket" }}
      targetPort: 80
{{- else }}
      targetPort: https
{{- end }}
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---
{{- end }}

